# Generated by Django 3.1.2 on 2020-10-14 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=500)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('Books', 'Books'), ('Home', 'Home'), ('Electronics', 'Electronics'), ('Vehicles', 'Vehicles'), ('Other', 'Other')], default='Other', max_length=32)),
                ('url', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
