# Generated by Django 3.1.2 on 2020-10-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watch_items', to='auctions.Listing'),
        ),
    ]
