# Generated by Django 3.1.2 on 2020-10-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201015_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watchlists',
            field=models.ManyToManyField(blank=True, to='auctions.Listing'),
        ),
    ]
