# Generated by Django 3.1.2 on 2020-10-15 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='create_date',
            new_name='create_bid',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='update_date',
            new_name='update_bid',
        ),
    ]
