# Generated by Django 3.1.2 on 2020-10-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
    ]
