# Generated by Django 3.1.2 on 2020-10-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='winner',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=256),
        ),
    ]
